### ISSUE TITLE
Upload smaller test data

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#11]
We need smaller test data as the `chr_array` jobs time out in Travis-CI (see [here](https://travis-ci.org/GooglingTheCancerGenome/CNN/jobs/627384998)).

**Comment by lsantuari** [comment]
We can either reduce chr22 (51Mb) to a region (ex. 1Mb) or use the mithocondrial (MT) DNA (16K). A smaller region would also mean less SVs. Is there an indication from Travis CI on what extent we should reduce the test set?
W.r.t. memory usage in `chr_array`, most of the memory is taken up by loading the Numpy arrays. I will check if I can reduce the memory usage.

**Comment by arnikz** [comment]
After merging your changes to the `chr_array` including some [modifications](ac0e692e251f), the Travis build still times out and a local run terminates on my laptop (>15G memory use). Could you prepare reduced data files?

**Comment by arnikz** [comment]
After merging your changes in `chr_array` (incl. some fixes) the [Travis build](https://travis-ci.org/GooglingTheCancerGenome/CNN/jobs/633962783) still fails:

```
/var/spool/gridengine/execd/8ec75217bbab/job_scripts/7: 22: /var/spool/gridengine/execd/8ec75217bbab/job_scripts/7: source: not found

Traceback (most recent call last):

  File "chr_array.py", line 346, in <module>

    main()

  File "chr_array.py", line 340, in main

    cmd_name=cmd_name

  File "chr_array.py", line 142, in create_hdf5

    chr_array = np.zeros(shape=(chrlen, n_channels), dtype=np.float32)

MemoryError: Unable to allocate array with shape (51304566, 46) and data type float32
```
Currently, builds are limited by 3GB of memory while the array requires 8 x 51304566 x 46 bytes or ~18GB. Nevertheless, jobs submitted to HPC/DAS nodes completed successfully in <10 min. Could you reduce the data files?

**Comment by arnikz** [comment]
Added in e1068cb6eed13b2d1232140526d5d52b2a03badb.
