### ISSUE TITLE
Describe the output of the chr_array.py script

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#14]
Please update [this](https://github.com/GooglingTheCancerGenome/CNN/wiki/Generation-of-chromosome-arrays) wiki page as done [here](https://github.com/GooglingTheCancerGenome/CNN/wiki/Description-of-output-files) for the other _channel_ scripts.

**Comment by lsantuari** [comment]
[Here](https://github.com/GooglingTheCancerGenome/CNN/wiki/Generation-of-chromosome-arrays) I added the channel specification for the `chr_array.py` output.
