### ISSUE TITLE
Enable all channels in chr_array.py

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#16]
There are some issues with these:

https://github.com/GooglingTheCancerGenome/CNN/blob/9be6d72028629129729c76c36b8fa1ace28c3095/scripts/genome_wide/chr_array.py#L161-L164

**Comment by arnikz** [comment]
@lsantuari could you look at this issue?

**Comment by lsantuari** [comment]
@arnikz All channels are enabled [here](https://github.com/GooglingTheCancerGenome/CNN/commit/ad387a98026d5d6e16aad4437a090b20c2214806).
