### ISSUE TITLE
Implement labeling modes

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#18]
Currently, we consider two modes:

- [x] [split read](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/scripts/genome_wide/label_window_pairs_on_split_read_positions.py)
- [x] [SV filtering](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/scripts/genome_wide/label_window_pairs_on_svcallset.py)

**Comment by arnikz** [comment]
@lsantuari: Could you add `[sv-callers].bedpe` files to the `data/test` dir? Please use the `iss18` branch.

**Comment by lsantuari** [comment]
The `--sv_caller` argument in `label_window_pairs_on_svcallset.py` is used to specify the candidate positions, taken from the GRIDSS or manta callsets. In the current implementation, the callsets are in BEDPE formats, so only the center positions of the breakpoint intervals are used. The original VCF output contains also the start and end of the confidence intervals for the breakpoints (CIPOS and CIEND), which can be taken into account. The `--ground_truth` argument in this case is used to compute the overlap between the candidate positions and the intervals of the truth set, to label the positions as either SV (DEL in case of deletions) or not SV (noDEL in case of deletions). I will add one script to convert the VCF files of the callers to BEDPE format.

**Comment by lsantuari** [comment]
Can you add the GRIDSS and manta VCF outputs produced by sv-callers on chr22.bam? I will convert them to BEDPE.

**Comment by lsantuari** [comment]
I added the VCF to BEDPE conversion [script](https://github.com/GooglingTheCancerGenome/CNN/blob/iss18/scripts/R/vcf2bedpe.R) to iss18.

**Comment by arnikz** [comment]
> Can you add the GRIDSS and manta VCF outputs produced by sv-callers on chr22.bam? I will convert them to BEDPE.

I've added _sv-callers_ output in VCF (https://github.com/GooglingTheCancerGenome/CNN/commit/b3e72ee80c82dd8c7eb7c5165dfc2e31b71f28c7) and BEDPE (6e9fc7d17efefaeb791e119f993e211b1f6f6424).

**Comment by arnikz** [comment]
@lsantuari: the `label_window_pairs_on_svcallset.py` is still failing while reading BEDPE (see [1](https://travis-ci.org/GooglingTheCancerGenome/CNN/jobs/642785970#L1322), [2](https://travis-ci.org/GooglingTheCancerGenome/CNN/jobs/642785970#L2044)). Also, `chr22.bedpe`(truth set) and `[sv-callers].bedpe` files differ in the number of columns (7 vs. 10). Could you check/fix?

**Comment by lsantuari** [comment]
The `[sv-callers].bedpe` that can be generated with [vcf2bedpe.R](https://github.com/GooglingTheCancerGenome/CNN/blob/iss18/scripts/R/vcf2bedpe.R) has now the same columns as `chr22.bedpe`.

**Comment by arnikz** [comment]
I've also added the R script to `run_local.sh` to generate the BEDPE files locally.
