### ISSUE TITLE
Pass user params to vcf2bedpe via CLI

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#20]
currently, these parameters are hard-coded:

- https://github.com/GooglingTheCancerGenome/CNN/blob/75a69f7f3c09a36c035d1d40e0bc69fb87ed67e8/scripts/R/vcf2bedpe.R#L15
- https://github.com/GooglingTheCancerGenome/CNN/blob/75a69f7f3c09a36c035d1d40e0bc69fb87ed67e8/scripts/R/vcf2bedpe.R#L53

**Comment by lsantuari** [comment]
I updated [vcf2bedpe.R](https://github.com/GooglingTheCancerGenome/CNN/blob/iss18/scripts/R/vcf2bedpe.R) to avoid hard coded parameters. (bff198303f57ca14b0533715601294cd038907a9)
