### ISSUE TITLE
Create window pairs from labeled data

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#26]

**Comment by arnikz** [comment]
@lsantuari: The `create_window_pairs.py` fails with the new test data (see [here](https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/662235203#L4569)). I've also ran it locally (use `iss27` branch)

```
./run_local.sh data/test/chr12_chr22.44Mb_45Mb.GRCh37.bam 12 22
...
+ python create_window_pairs.py -b data/test/chr12_chr22.44Mb_45Mb.GRCh37.bam -c 22 -sv gridss -w 200 -p . -l create_window_pairs.log
Traceback (most recent call last):
  File "create_window_pairs.py", line 275, in <module>
    main()
  File "create_window_pairs.py", line 267, in main
    npz_mode=args.save_npz
  File "create_window_pairs.py", line 171, in get_windows
    d = chr_array[chr1][pos1 - win_hlen:pos1 + win_hlen, :]
KeyError: '12'

cat scripts/genome_wide/windows/create_window_pairs.log 
2020-03-14 10:09:19,788 Loading file: ./chr_array/22_carray
2020-03-14 10:09:19,797 Array shape: (1000000, 46)
2020-03-14 10:09:19,798 46 channels
2020-03-14 10:09:19,801 593 labels found: Counter({'DEL': 568, 'UK_single_partial': 20, 'noDEL': 4, 'UK_multiple_on_either_windows': 1})
2020-03-14 10:09:19,802 Creating test...
2020-03-14 10:09:19,852 Creating dask_arrays_win1 and dask_arrays_win2...
2020-03-14 10:09:19,852 chr1=12 pos1=392083 chr2=12 pos2=392614
```

**Comment by lsantuari** [comment]
`label_window_pairs_on_split_read_positions`, `label_window_pairs_on_svcallset` and `create_window_pairs` should be outside of the _for_ loop (see [here](https://github.com/GooglingTheCancerGenome/CNN/blob/63c3a17bdcde62497fed261132776b192e7c61e0/run_local.sh#L61))

**Comment by arnikz** [comment]
> `label_window_pairs_on_split_read_positions`, `label_window_pairs_on_svcallset` and `create_window_pairs` should be outside of the _for_ loop (see [here](https://github.com/GooglingTheCancerGenome/CNN/blob/63c3a17bdcde62497fed261132776b192e7c61e0/run_local.sh#L61))

In the commit 9688e3eb79a5f8bbceea71742590c0cda53ba9d6 this has been addressed (see [here](https://github.com/GooglingTheCancerGenome/CNN/blob/9688e3eb79a5f8bbceea71742590c0cda53ba9d6/run_local.sh#L66-L73)) but the `chr_array` jobs still fail for the same reason.

See job accounting info:
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/665253281#L5828
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/665253281#L6662

and stderr logs:
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/665253281#L7029
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/665253281#L7076

Could you investigate further?

**Comment by lsantuari** [comment]
This issue can be closed.
