### ISSUE TITLE
Implement training/testing of the models in cross-validation

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#27]
- [x] targeted mode based on split-reads
- [x] targeted mode based on SV callsets

**Comment by arnikz** [comment]
@lsantuari: currently the script is executed in the cross-validation mode. Could you check [these](https://travis-ci.org/GooglingTheCancerGenome/CNN/jobs/647258802#L5976-L6028) lines of the error log?

**Comment by arnikz** [comment]
After `run_docker.sh` I'm getting  errors like these for many channel scripts:

```
### ./stderr-4.log ###
+ cat ./stderr-4.log
Traceback (most recent call last):
  File "split_reads.py", line 423, in <module>
    main()
  File "split_reads.py", line 400, in main
    os.makedirs(output_dir, exist_ok=True)
  File "/home/xenon/miniconda/envs/wf/lib/python3.6/os.py", line 210, in makedir
s
    makedirs(head, mode, exist_ok)
  File "/home/xenon/miniconda/envs/wf/lib/python3.6/os.py", line 210, in makedir
s
    makedirs(head, mode, exist_ok)
  File "/home/xenon/miniconda/envs/wf/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/xenon/miniconda/envs/wf/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'
```
The `/Users...` path is the [default value](https://github.com/GooglingTheCancerGenome/CNN/blob/3de7a0f8f9872eb960a833922aa6e51cd7a54d1c/scripts/genome_wide/split_reads.py#L388) for the `-p | --outputpath` arg but the scripts are called with the current [workdir](https://github.com/GooglingTheCancerGenome/CNN/blob/16e5485bf85ffd4d927de57b146efd33cb9ec9d9/run.sh#L21) using [`-p .`](https://github.com/GooglingTheCancerGenome/CNN/blob/3de7a0f8f9872eb960a833922aa6e51cd7a54d1c/run.sh#L59). Looks like a problem with quotes...

**Comment by arnikz** [comment]
@lsantuari have you committed the latest `run_local.sh`?

```
Writing log file to labels/win200/INS/gridss/train_model_with_fit/train_model_with_fit.log
Traceback (most recent call last):
  File "train_model_with_fit.py", line 765, in <module>
    main()
  File "train_model_with_fit.py", line 757, in main
    kfold=args.kfold)
  File "train_model_with_fit.py", line 511, in cross_validation
    X, y, win_ids = get_data(os.path.join(outDir, '..'), npz_mode, svtype)
  File "train_model_with_fit.py", line 279, in get_data
    X, y, win_ids = filter_labels(X, y, win_ids)
  File "train_model_with_fit.py", line 193, in filter_labels
    X = X[np.array(keep)]
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by lsantuari** [comment]
Fixed in 93d82132d8a7fa26adb841c267850a9994618957

**Comment by arnikz** [comment]
btw. the output dirs include many `train_._test_._cv[1-3]` (sub)dirs. It looks like some parameter(s) is missing.

**Comment by arnikz** [comment]
Working on it...

**Comment by arnikz** [comment]
Working on it...

**Comment by arnikz** [comment]
Note there yet: jobs fail starting from [`stderr-10.log`](https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/666573773#L9155) and so forth.

**Comment by lsantuari** [comment]
I think the [problem](https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/666573773#L9101) is that the list of chromosome (['12', '22']) is recognized as a string ("12 22"). It should be `12 22` and not `"12 22"`.
Try to [remove the quotes](https://github.com/GooglingTheCancerGenome/CNN/blob/270404201c3b242a9c09256f9c65ba7164619ff5/run_local.sh#L44) in each instance of `${SEQ_IDS[@]}` in the `run.sh` script:

`from "${SEQ_IDS[@]}" to ${SEQ_IDS[@]}`

**Comment by arnikz** [comment]
> I think the [problem](https://travis-ci.org/github/GooglingTheCancerGenome/CNN/jobs/666573773#L9101) is that the list of chromosome (['12', '22']) is recognized as a string ("12 22"). It should be `12 22` and not `"12 22"`.
> Try to [remove the quotes](https://github.com/GooglingTheCancerGenome/CNN/blob/270404201c3b242a9c09256f9c65ba7164619ff5/run_local.sh#L44) in each instance of `${SEQ_IDS[@]}` in the `run.sh` script:
> 
> `from "${SEQ_IDS[@]}" to ${SEQ_IDS[@]}`

That's not a good idea. The linter will complain:

 _Double quote array expansions to avoid re-splitting elements. [SC2068]_.

Moreover, you referred to `run_local.sh`, which runs just fine. In `run.sh` each job command must be stored in a variable and hence the quotation changes for the reasons above. Please, update the CLI of each script to parse `-c  X,Y,...` (safer) instead of `-c "X Y"`.

**Comment by lsantuari** [comment]
> btw. the output dirs include many `train_._test_._cv[1-3]` (sub)dirs. It looks like some parameter(s) is missing.

The input parameters of the [training/testing script](https://github.com/GooglingTheCancerGenome/CNN/blob/iss27/scripts/genome_wide/train_model_with_fit.py) for the [training sample](https://github.com/GooglingTheCancerGenome/CNN/blob/5652a06ebd22ac66b80fb5f71eed0a5f8631798a/scripts/genome_wide/train_model_with_fit.py#L669) and the [test sample](https://github.com/GooglingTheCancerGenome/CNN/blob/5652a06ebd22ac66b80fb5f71eed0a5f8631798a/scripts/genome_wide/train_model_with_fit.py#L674) point to the working folders for the training and test samples respectively. In case of our test data, training and test sample folders are the same (the current folder: `.`). The working folder name, which should be the same as the sample name, is used for naming the output folder, in this case `train_._test_._cv[1-3]`.
I will add training/test sample names as separate arguments in the [script](https://github.com/GooglingTheCancerGenome/CNN/blob/iss27/scripts/genome_wide/train_model_with_fit.py).

**Comment by arnikz** [comment]
`run_local.sh` is currently broken (see #32 and #33) - a prerequisite to continue further with `run.sh`

**Comment by arnikz** [comment]
Let's try to make further commits as atomic as possible (i.e., break-down into issues followed by merge into the `iss27` branch once fixed).

**Comment by arnikz** [comment]
Shall I close this issue?
