### ISSUE TITLE
Add new test data

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#28]
The `htz-sv.bam` sample should include more INDELs (#27) and at least two chromosomes.

**Comment by lsantuari** [comment]
I added a new branch [here](https://github.com/GooglingTheCancerGenome/CNN/tree/iss28) with the new test data.

**Comment by arnikz** [comment]
The new 2bit file contains seqIDs in the form `chr:start-end` instead of the form `chr` as in the original file. 

```python
import twobitreader as twobit
print(twobit.TwoBitFile('data/test/chr12_chr22.44Mb_45Mb.GRCh37.2bit').keys())
dict_keys(['12:44000000-45000000', '22:44000000-45000000'])

print(twobit.TwoBitFile('data/test/chr22.2bit').keys())
dict_keys(['22'])
```
