### ISSUE TITLE
VCF to BEDPE conversion for SURVIVOR simSV output

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/CNN#30]
The VCF output of _sv-gen_ needs to be converted in BEDPE format.
The [awk script](https://github.com/GooglingTheCancerGenome/CNN/blob/63c3a17bdcde62497fed261132776b192e7c61e0/run_local.sh#L25) should be replaced with the [vcf2bedpe.R](https://github.com/GooglingTheCancerGenome/CNN/blob/63c3a17bdcde62497fed261132776b192e7c61e0/run_local.sh#L32) script.

**Comment by arnikz** [comment]
AFAIK, this has not been addressed in https://github.com/GooglingTheCancerGenome/CNN/commit/d3adb675c06f2854878e4df9c18e1e7271803aa0.

**Comment by arnikz** [comment]
Both commits address data rather than this code-related issue. The idea is to abandon [this](https://github.com/GooglingTheCancerGenome/CNN/blob/ab9e4666e7e94c7f476266441631d0beb0bf1a8c/run_local.sh#L28) code (and TSV file) in favour of [this](https://github.com/GooglingTheCancerGenome/CNN/blob/ab9e4666e7e94c7f476266441631d0beb0bf1a8c/run_local.sh#L33) one. Do you agree?

**Comment by lsantuari** [comment]
I agree. However, StructuralVariantAnnotation does not support the SURVIVOR VCF file by default. This is required for [vcf2bed.R](https://github.com/GooglingTheCancerGenome/CNN/blob/ab9e4666e7e94c7f476266441631d0beb0bf1a8c/run_local.sh#L37) to work. I am testing it in #36 with the [notebook](https://github.com/GooglingTheCancerGenome/CNN/blob/iss36/scripts/R/notebooks/Benchmark.ipynb) used to generate the benchmark plots.

**Comment by arnikz** [comment]
> I agree. However, StructuralVariantAnnotation does not support the SURVIVOR VCF file by default. This is required for [vcf2bed.R](https://github.com/GooglingTheCancerGenome/CNN/blob/ab9e4666e7e94c7f476266441631d0beb0bf1a8c/run_local.sh#L37) to work. I am testing it in #36 with the [notebook](https://github.com/GooglingTheCancerGenome/CNN/blob/iss36/scripts/R/notebooks/Benchmark.ipynb) used to generate the benchmark plots.

OK. Didn't we decide to use the callers' output directly instead of SURVIVOR VCFs?

**Comment by lsantuari** [comment]
Yes. Sorry for the confusion. I am referring to [the VCF file](https://github.com/GooglingTheCancerGenome/CNN/blob/iss27/data/test/htz-sv.vcf) that SURVIVOR simSV outputs and that we are using as a truth set for the artificial data.
