### ISSUE TITLE
snv.py script fails

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#33]
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/builds/666951796#L983-L997

**Comment by lsantuari** [comment]
Fixed in d3adb675c06f2854878e4df9c18e1e7271803aa0

**Comment by arnikz** [comment]
Yes, works fine according to:
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/builds/666983496#L973
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/builds/666983496#L982
