### ISSUE TITLE
Update & clean-up test data dir

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#34]
https://github.com/GooglingTheCancerGenome/CNN/tree/iss27/data/test.

For example:

- the callers' `.bedpe` files seems outdated:
 
```bash
for c in manta delly lumpy gridss; do echo $c; cut -f 1 $c.bedpe|sort -u; done
manta
22
delly
22
lumpy
22
gridss
22
```
 SVs only on chr. 22 but the latest VCF files include SVs on both chr. 12 and 22!

```bash
for f in $(find data/test/vcf/*/survivor -name *.vcf); do echo $f; bcftools view -H $f |cut -f 1|sort -u; done
data/test/vcf/delly_out/survivor/delly.vcf
12
22
data/test/vcf/gridss_out/survivor/gridss.vcf
12
22
data/test/vcf/lumpy_out/survivor/lumpy.vcf
[W::vcf_parse] Contig '12' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '22' is not defined in the header. (Quick workaround: index the file with tabix.)
12
22
data/test/vcf/manta_out/survivor/manta.vcf
12
22
```

- SV truth sets (`.vcf` vs. `.tsv|.bedpe`) are not consistent regarding SV types / counts (see #30):

```bash
bcftools view -H htz-sv.vcf|cut -f 5|sort|uniq -c
[W::vcf_parse] FILTER 'LowQual' is not defined in the header
[W::vcf_parse] INFO 'PRECISE' is not defined in the header, assuming Type=String
    982 <DEL>
   1000 <DUP>
   1018 <INS>
   1000 <INV>
   2000 <TRA>

wc -l chr12_chr22.44Mb_45Mb.GRCh37.tsv
6000 chr12_chr22.44Mb_45Mb.GRCh37.tsv

wc -l chr12_chr22.44Mb_45Mb.GRCh37.bedpe
2000 chr12_chr22.44Mb_45Mb.GRCh37.bedpe

cut -f 7 chr12_chr22.44Mb_45Mb.GRCh37.bedpe|sort|uniq -c
   1009 DEL
    991 INS
```

**Comment by lsantuari** [comment]
Fixed in 94cd15052fc6ee52a5e7938ca9cb71ae9881a7ea

Now the callers' `bedpe` are correct:

```
for c in manta delly lumpy gridss; do echo $c; cut -f 1 $c.bedpe|sort -u; done
manta
12
22
delly
12
22
lumpy
12
22
gridss
12
22
```
Regarding:

```
bcftools view -H htz-sv.vcf|cut -f 5|sort|uniq -c
[W::vcf_parse] FILTER 'LowQual' is not defined in the header
[W::vcf_parse] INFO 'PRECISE' is not defined in the header, assuming Type=String
    982 <DEL>
   1000 <DUP>
   1018 <INS>
   1000 <INV>
   2000 <TRA>
```

I run sv-gen with 1000 SVs for each SV types:

- `<TRA>` have two entries per SV, because they are balanced translocations specified by two different breakpoints
- SURVIVOR simSV in sv-gen allows you to set a number for SV type INDEL, that is either INS or DEL. It will try to create half of one type and half of the other, if possible. However, our test data shows that it is not guaranteed to return half INS and half DEL

`chr12_chr22.44Mb_45Mb.GRCh37.bedpe` is correct now:

```
cut -f 7 chr12_chr22.44Mb_45Mb.GRCh37.bedpe|sort|uniq -c
 982 DEL
1000 DUP
1018 INS
1000 INV
2000 TRA
```

Different SV callers call different sets of SV types, so I will have to take care of that:

```
for c in manta delly lumpy gridss; do echo $c; cut -f 7 $c.bedpe|sort -u; done
manta
DEL
INS
delly
DEL
DUP
INS
INV
lumpy
DEL
DUP
INV
TRA
gridss
DEL
DUP
INS
INV
TRA
```
I updated `vcf2bedpe.R` to use `TRA` (as SURVIVOR specifies translocations) instead of `BP` (as translocations are specified in the [SV benchmark](https://github.com/PapenfussLab/sv_benchmark).

**Comment by arnikz** [comment]
In addition to #38 and [this](https://github.com/GooglingTheCancerGenome/CNN/tree/dev/scripts/benchmark) dir, can I also delete the following files following the discussion in https://github.com/GooglingTheCancerGenome/CNN/issues/30#issuecomment-604981862?

```
data/htz-sv.bed
data/test.tsv
data/vcf/all.vcf
data/vcf/delly_out/survivor/delly.vcf
data/vcf/gridss_out/survivor/gridss.vcf
data/vcf/lumpy_out/survivor/lumpy.vcf
data/vcf/manta_out/survivor/manta.vcf
```

**Comment by lsantuari** [comment]
We can delete:

```
data/test.tsv
data/vcf/all.vcf
data/vcf/delly_out/survivor/delly.vcf
data/vcf/gridss_out/survivor/gridss.vcf
data/vcf/lumpy_out/survivor/lumpy.vcf
data/vcf/manta_out/survivor/manta.vcf
```

We are still using `data/htz-sv.bed` for the moment, until we can switch to `data/htz-sv.vcf`.

**Comment by arnikz** [comment]
> We are still using `data/htz-sv.bed` for the moment, until we can switch to `data/htz-sv.vcf`.

True, however, I'm fixing #30 so this file won't be needed.

**Comment by arnikz** [comment]
Ah typo, I mean `unnecessary` files in https://github.com/GooglingTheCancerGenome/CNN/commit/3f24af4ccb160096346252f546ad8f63fb49dabe.
