### ISSUE TITLE
Write Jupyter notebook to generate benchmark's plots and tables

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/CNN#36]
The notebook should take in input:

- the CNN BEDPE output
- the SV callers VCF files
- the truth set

It should generate:

- a Precision-Recall plot at multiple SV QUAL thresholds
- a table with Precision, Recall, F1-score, #TP, #FP at each QUAL threshold

**Comment by arnikz** [comment]
Some duplication here:
```
cd ./scripts/R/notebooks/
md5sum Benchmark.ipynb  Benchmark/* 
2487debbf694349886bf9f2ea0823754  Benchmark.ipynb
0ee1a18a9f9437f440cf272c6d57e92b  Benchmark/Benchmark.ipynb
2487debbf694349886bf9f2ea0823754  Benchmark/Benchmark plots.ipynb
```
