### ISSUE TITLE
Personalis 1kGP SV truth set

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#38]
Do we use or need to store [this](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/NA12878/Personalis_1000_Genomes_deduplicated_deletions.bedpe) file in the repo?

**Comment by lsantuari** [comment]
We are not using that file in the test, so we can delete the [folder](https://github.com/GooglingTheCancerGenome/CNN/tree/dev/data/NA12878). We can also delete [this](https://github.com/GooglingTheCancerGenome/CNN/tree/dev/scripts/benchmark) folder.

**Comment by lsantuari** [comment]
I cannot see [this](https://github.com/GooglingTheCancerGenome/CNN/tree/dev/scripts/benchmark) folder in my local checkout of dev, but it is still present in the online repo. Do you know why?
