### ISSUE TITLE
Document the generation of test data

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#40]
see https://github.com/GooglingTheCancerGenome/sv-channels/tree/dev/data (related to #47)

**Comment by lsantuari** [comment]
Very good point, @arnikz. I will take care of it.

**Comment by lsantuari** [comment]
The README updated with the commands used to generate the test data is already in [dev](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/README.md) (504b4ea6f221f2b0d93b1cbdcc681abd90bc94e9).

**Comment by arnikz** [comment]
Thanks. Pls fork/add to the leading branch (`iss32`) in the future. From now on, commits to `dev` are not possible without PR.

**Comment by arnikz** [comment]
Please document the provenance of all files in the `data` dir (e.g. _sv-gen_ files).
