### ISSUE TITLE
Execution halted: vcf2bedpe.R

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#43]
https://travis-ci.org/github/GooglingTheCancerGenome/CNN/builds/667785627#L762

**Comment by lsantuari** [comment]
I could:

- [ ]  open an issue on [StructuralVariantAnnotation](https://github.com/PapenfussLab/StructuralVariantAnnotation).
- [x] modify the SURVIVOR simSV VCF file to be read correctly by StructuralVariantAnnotation

It seems to recognize the SURVIVOR simSV VCF file as a Delly VCF file, with the missing [CT](https://groups.google.com/d/msg/delly-users/6Mq2juBraRY/zdNt7sTZyIsJ) field.

**Comment by arnikz** [comment]
That's fine. For time being, a quick fix is to limit the VCF->BEDPE to GRIDSS

https://github.com/GooglingTheCancerGenome/CNN/blob/787d879145e3ad41a164ee07b2285515310daadb/run_local.sh#L16

**Comment by lsantuari** [comment]
Converting the [truth set](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/htz-sv.vcf) of the artificial SVs into BEDPE is still necessary to compare the GRIDSS callset to. See [here](https://github.com/GooglingTheCancerGenome/CNN/blob/66292207e71a1b4fbbbf285a49bd4fc71685a8ec/run_local.sh#L72) and [here](https://github.com/GooglingTheCancerGenome/CNN/blob/66292207e71a1b4fbbbf285a49bd4fc71685a8ec/run_local.sh#L87), for instance. So this issue is on my priority list, also for #36 and #41.

**Comment by lsantuari** [comment]
Adding an extra step to treat `TRA` as `CTX` is a quick fix at the moment:

`sed 's/TRA/CTX/g' htz-sv.vcf > htz-sv_CTX.vcf`

and then using `htz-sv_CTX.vcf` as `test.vcf`

**Comment by arnikz** [comment]
> Converting the [truth set](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/htz-sv.vcf) of the artificial SVs into BEDPE is still necessary to compare the GRIDSS callset to. See [here](https://github.com/GooglingTheCancerGenome/CNN/blob/66292207e71a1b4fbbbf285a49bd4fc71685a8ec/run_local.sh#L72) and [here](https://github.com/GooglingTheCancerGenome/CNN/blob/66292207e71a1b4fbbbf285a49bd4fc71685a8ec/run_local.sh#L87), for instance. So this issue is on my priority list, also for #36 and #41.

Yes, I want to use `test.vcf` and `gridss.vcf` as a quick fix  for `run_local.sh`

**Comment by arnikz** [comment]
> Adding an extra step to treat `TRA` as `CTX` is a quick fix at the moment:
> 
> `sed 's/TRA/CTX/g' htz-sv.vcf > htz-sv_CTX.vcf`
> 
> and then using `htz-sv_CTX.vcf` as `test.vcf`

Let's keep the data as is.

**Comment by lsantuari** [comment]
As a reference, treating SURVIVOR simSV TRA SVs as [TIGRA](https://bioinformatics.mdanderson.org/public-software/archive/tigra/) [CTX SVs](https://github.com/PapenfussLab/StructuralVariantAnnotation/blob/baadd66ef54d5e209852d8991afa809edb014348/R/extensions-VCF.R#L494) seems to work.

**Comment by lsantuari** [comment]
> > Adding an extra step to treat `TRA` as `CTX` is a quick fix at the moment:
> > `sed 's/TRA/CTX/g' htz-sv.vcf > htz-sv_CTX.vcf`
> > and then using `htz-sv_CTX.vcf` as `test.vcf`
> 
> Let's keep the data as is.

I agree.

**Comment by arnikz** [comment]
nope
https://github.com/GooglingTheCancerGenome/CNN/blob/ea119778d8b455c26ddf258107e548895597ee05/run_local.sh#L28

**Comment by arnikz** [comment]
It wasn't a quick fix after all :wink:

https://github.com/GooglingTheCancerGenome/CNN/blob/a276f179aae28cfbe6d860e97df32afd1afbe05c/run_local.sh#L28

:roll_eyes:  Where did DELLY come from? I missed your https://github.com/GooglingTheCancerGenome/CNN/issues/43#issuecomment-605111365.

Moreover, diff  `iss32` (broken) and `dev` branch (passes) shows change:  `TRA`->`BP`.

**Comment by lsantuari** [comment]
> It wasn't a quick fix after all 😉
> 
> https://github.com/GooglingTheCancerGenome/CNN/blob/a276f179aae28cfbe6d860e97df32afd1afbe05c/run_local.sh#L28
> 
> 🙄 Where did DELLY come from? I missed your [#43 (comment)](https://github.com/GooglingTheCancerGenome/CNN/issues/43#issuecomment-605111365).

If you process the [SURVIVOR VCF file with the artificial SVs](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/htz-sv.vcf) with [breakpointRanges](https://github.com/GooglingTheCancerGenome/CNN/blob/504b4ea6f221f2b0d93b1cbdcc681abd90bc94e9/scripts/R/vcf2bedpe.R#L72) you get the following error:

```
There were 16 warnings (use warnings() to see them)
Warning message:
package ‘argparser’ was built under R version 3.6.2
Error in .breakpointRanges(x, ...) : Delly variants missing CT:
Calls: breakpointRanges -> breakpointRanges -> .breakpointRanges
In addition: Warning message:
In .breakpointRanges(x, ...) :
  Found 1000 duplicate row names (duplicates renamed).
Execution halted
```

This is because SURVIVOR, like DELLY, uses the SVTYPE `TRA` for translocations, instead of BP (GRIDSS) or CTX (TIGRA).

> Moreover, diff `iss32` (broken) and `dev` branch (passes) shows change: `TRA`->`BP`.

**Comment by arnikz** [comment]
OK. It's still unclear to me which of the three (`TRA`, `BP` or `CTX`) should be used in this script to pass and/or to resolve merge conflicts in the branches?

**Comment by arnikz** [comment]
> If you process the [SURVIVOR VCF file with the artificial SVs](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/data/htz-sv.vcf) with [breakpointRanges](https://github.com/GooglingTheCancerGenome/CNN/blob/504b4ea6f221f2b0d93b1cbdcc681abd90bc94e9/scripts/R/vcf2bedpe.R#L72) you get the following error:

Yes, the very same error shown [here](https://travis-ci.org/github/GooglingTheCancerGenome/CNN/builds/667830402#L759).

**Comment by lsantuari** [comment]
> OK. It's still unclear to me which of the three (`TRA`, `BP` or `CTX`) should be used in this script to pass and/or to resolve merge conflicts in the branches?

`CTX`

`vcf2bedpe.R` works with `test.vcf` when all the occurrence of `TRA` are substituted with `CTX`:

`sed 's/TRA/CTX/g' test.vcf`

However, you still have to direct the output of `sed` to an intermediate file that is used in input to `vcf2bedpe.R`.

**Comment by arnikz** [comment]
Last commit passes but the code does not make use of the VCF file. Please fork the `iss32` instead of `dev` to continue.

**Comment by lsantuari** [comment]
Done. Branch [iss43](https://github.com/GooglingTheCancerGenome/CNN/tree/iss43) can be deleted.
