### ISSUE TITLE
Do not filter split read positions

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/CNN#54]
Avoid filtering split read positions with clipped read positions in the labelling script.

Leave out [this](https://github.com/GooglingTheCancerGenome/CNN/blob/bae582ef5de7b58bad30e92980c0cdce31c1043d/scripts/genome_wide/functions.py#L468) block of code.

**Comment by arnikz** [comment]
Fixed in 9a8e562
