### ISSUE TITLE
GEM indexer fails

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#60]
```
+ ../mappability/run_gem.sh hs37d5 /home/arnikz/Downloads/gitrepos/GTCG/sv-channels/scripts/utils/hs37d5.fa 30 .
...
GEM::FatalError (mm.c:142,mm_malloc_)
 Could not allocate memory (5800869765Bytes requested)
```

related to #59

**Comment by lsantuari** [comment]
To reduce the memory needed for the execution of GEM indexer, we should run it only with the [test data sequences](https://github.com/GooglingTheCancerGenome/sv-channels/blob/dev/data/test.fasta).

**Comment by arnikz** [comment]
OK. Check if you succeed by following the [README](https://github.com/GooglingTheCancerGenome/sv-channels/blob/dev/scripts/utils/README.md).

**Comment by lsantuari** [comment]
Support for `gem-mappability` and `gem-2-wig` was dropped in newer versions of GEM. The [conda](https://anaconda.org/bioconda/gem3-mapper) version does not have these commands.
[genmap](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa222/5815974) looks like the ideal replacement, but the [conda installation](https://anaconda.org/bioconda/genmap) on my `osx-64` [does not work](https://github.com/cpockrandt/genmap/issues/17). I will try it on `linux`.

**Comment by lsantuari** [comment]
@arnikz genmap works in place of GEM:

Using K equal to BWA mem seed length (19) and maximum 2 mismatches.

To be added to environment.yml

```
channels
 - bioconda
dependencies
 - genmap=1.2.0=h6de7cb9_0
 - ucsc-bedgraphtobigwig=357=1
```

In the sv-channels repo:
```
cd scripts/utils
genmap index -F ../../data/test.fasta -I genmap_index
genmap map -K 19 -E 2 -I genmap_index -O genmap_K19_E2 -bg
```
generate file with chromosome sizes:
```
cut -f1,2 ../../data/test.fasta.fai > ../../data/test.chrsizes
```
convert bedgraph to bigwig:
```
bedGraphToBigWig genmap_K19_E2.bedgraph ../../data/test.chrsizes ../../data/test.bw
```

@arnikz can you add it to the run.sh script?

**Comment by arnikz** [comment]
@lsantuari: Could you look at [this](https://travis-ci.org/github/GooglingTheCancerGenome/sv-channels/jobs/745398107#L4992) and [this](https://travis-ci.org/github/GooglingTheCancerGenome/sv-channels/jobs/745377104#L4953) log? It seems related to this discrepancy in chromosome lengths:

```
# original BigWig file
bigWigInfo -chroms data/test.bw 
version: 4
isCompressed: yes
isSwapped: 0
primaryDataSize: 102,397
primaryIndexSize: 404
zoomLevels: 2
chromCount: 2
	12 0 133851895
	22 1 51304566
basesCovered: 4,026,619
mean: 0.977269
min: 0.000231
max: 1.000000
std: 0.139225
```


```
# new BigWig file generated by genmap.sh
bigWigInfo -chroms test.bw 
version: 4
isCompressed: yes
isSwapped: 0
primaryDataSize: 5,293,285
primaryIndexSize: 46,680
zoomLevels: 9
chromCount: 2
	12 0 2000000
	22 1 2000000
basesCovered: 3,999,964
mean: 0.738187
min: 0.000165
max: 1.000000
std: 0.381573
```

**Comment by lsantuari** [comment]
1e878fb fixes the problem with the discrepancy in chromosome lengths.
