### ISSUE TITLE
Generating all the necessary files in the data directory

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/CNN#76]
sv-channels should take in input:

- a BAM file (symlinked to test.bam) generated by mapping the reads (FASTQ format) to the reference sequence (FASTA format) with a read mapper that supports split read mapping, such as BWA mem;
- the reference sequence (symlinked to test.fasta) in FASTA format that was used to map the reads.

All the other files in the _data_ directory must be generated from either the BAM file or the FASTA file:

- [x] the FASTA index test.fasta.fai
- [x] the file [reference_N_regions.bed](https://github.com/GooglingTheCancerGenome/sv-channels/blob/iss64/data/reference_N_regions.bed) generated with [Ns_to_bed.py](https://github.com/GooglingTheCancerGenome/sv-channels/blob/iss64/scripts/utils/Ns_to_bed.py);
- [ ] the file [seqs.bed](https://github.com/GooglingTheCancerGenome/sv-channels/blob/iss64/data/seqs.bed) generated from  the FASTA index test.fasta.fai;
- [x] the file test.2bit generated with faToTwoBit

**Comment by arnikz** [comment]
> - the file seqs.bed generated from  the FASTA index test.fasta.fai;


@lsantuari: Could you clarify how did you get

https://github.com/GooglingTheCancerGenome/sv-channels/blob/9866b35d93ea4121c0bbe92b847ab95f590423be/data/seqs.bed#L1-L2

from

https://github.com/GooglingTheCancerGenome/sv-channels/blob/9866b35d93ea4121c0bbe92b847ab95f590423be/data/test.fasta.fai#L1-L2 ?

**Comment by arnikz** [comment]
> - the file test.2bit generated with faToTwoBit
> - the file reference_N_regions.bed generated with Ns_to_bed.py;

@lsantuari: Accordingly, I got an empty BED file.

```
faToTwoBit test.fasta test.2bit
python Ns_to_bed.py -b reference_N_regions.bed -t test.2bit -c 12,22
```
related to #79

**Comment by lsantuari** [comment]
> > * the file test.2bit generated with faToTwoBit
> > * the file reference_N_regions.bed generated with Ns_to_bed.py;
> 
> @lsantuari: Accordingly, I got an empty BED file.
> 
> ```
> faToTwoBit test.fasta test.2bit
> python Ns_to_bed.py -b reference_N_regions.bed -t test.2bit -c 12,22
> ```
> 
> related to #79

It is correct. It means that there are no genomic intervals containing only ambiguous bases (represented by 'N' in this case) in our test 'reference genome'. Our test.fasta file contains:
- chromosome 12 from position 44000000 to position 46000000
- chromosome 22 from position 44000000 to position 46000000

**Comment by lsantuari** [comment]
> > * the file seqs.bed generated from  the FASTA index test.fasta.fai;
> 
> @lsantuari: Could you clarify how did you get
> 
> https://github.com/GooglingTheCancerGenome/sv-channels/blob/9866b35d93ea4121c0bbe92b847ab95f590423be/data/seqs.bed#L1-L2
> 
> from
> 
> https://github.com/GooglingTheCancerGenome/sv-channels/blob/9866b35d93ea4121c0bbe92b847ab95f590423be/data/test.fasta.fai#L1-L2
> 
> ?

seqs.bed is an old version, where the values were hard-coded, and it must be replaced.

BED is [0-based](https://m.ensembl.org/info/website/upload/bed.html), so the file _seqs.bed_ should be:
```
12	0	1999999
22	0	1999999
```
which can be obtained from the FASTA index _test.fasta.fai_ with the following command:
```
awk '{print $1 "\t0\t" $2-1}' test.fasta.fai > seqs.bed
```

**Comment by arnikz** [comment]
@lsantuari: Could you clarify the purpose of these?
```
$ ls data/ *.bed
ENCFF001TDO.bed  reference_N_regions.bed  seqs.bed  test.bed  # the latter is a symlink to seqs.bed
```
- `EXCL_LIST=ENCFF001TDO.bed` - used by `merge_sv_calls.R`
- `REF_REG=reference_N_regions.bed` - used by `merge_sv_calls.R`
- `BED=test.bed` - used by `label_windows.py`.

**Comment by lsantuari** [comment]
> @lsantuari: Could you clarify the purpose of these?
> 
> ```
> $ ls data/ *.bed
> ENCFF001TDO.bed  reference_N_regions.bed  seqs.bed  test.bed  # the latter is a symlink to seqs.bed
> ```
> 
> * `EXCL_LIST=ENCFF001TDO.bed` - used by `merge_sv_calls.R`

The ENCODE blacklist is used to filter out SVs that falls in these regions. However, the same filtering is also performed in the downstream analysis, for instance in [generate_figure2.R](https://github.com/GooglingTheCancerGenome/sv-channels/blob/iss64-svtypes/scripts/R/generate_figure2.R), so it is not necessary at this stage

> * `REF_REG=reference_N_regions.bed` - used by `merge_sv_calls.R`

The BED file with intervals containing Ns are used to make sure that no SVs overlap with these regions. As for the ENCODE blacklist, this filtering is also performed in the downstream analysis and therefore it is not necessary at this stage

> * `BED=test.bed` - used by `label_windows.py`.

this is used as a check to make sure that we only consider genomic positions in the chromosome intervals. It is used in the function [chr_dict_from_bed](https://github.com/GooglingTheCancerGenome/sv-channels/blob/27a24d578e34469af092d17f334ea70cdb79a548/scripts/genome_wide/functions.py#L590) in [functions.py](https://github.com/GooglingTheCancerGenome/sv-channels/blob/27a24d578e34469af092d17f334ea70cdb79a548/scripts/genome_wide/functions.py) and called [here](https://github.com/GooglingTheCancerGenome/sv-channels/blob/27a24d578e34469af092d17f334ea70cdb79a548/scripts/genome_wide/label_windows.py#L450).
This file could be replaced by using only the FASTA index test.fasta.fai

**Comment by arnikz** [comment]
> this is used as a check to make sure that we only consider genomic positions in the chromosome intervals. It is used in the function chr_dict_from_bed in functions.py and called here.
This file could be replaced by using only the FASTA index test.fasta.fai

@lsantuari: Are you sure it's always 1:1 correspondence between FASTA/FAI and BED? I'll change the code accordingly (e.g., using `pysam`).

**Comment by lsantuari** [comment]
> > this is used as a check to make sure that we only consider genomic positions in the chromosome intervals. It is used in the function chr_dict_from_bed in functions.py and called here.
> > This file could be replaced by using only the FASTA index test.fasta.fai
> 
> @lsantuari: Are you sure it's always 1:1 correspondence between FASTA/FAI and BED? I'll change the code accordingly (e.g., using `pysam`).

@arnikz Yes. Basically what we need are the chromosome IDs and lengths (first and second columns of the FASTA.FAI index).

**Comment by arnikz** [comment]
> Yes. Basically what we need are the chromosome IDs and lengths (first and second columns of the FASTA.FAI index).

Just to make sure: `length` or `length - 1`?

https://github.com/GooglingTheCancerGenome/sv-channels/blob/9866b35d93ea4121c0bbe92b847ab95f590423be/data/test.fasta.fai#L1-L2

gives

```
$ awk '{print $1 "\t0\t" $2-1}' test.fasta.fai
12	0	1999999
22	0	1999999
```

previously
https://github.com/GooglingTheCancerGenome/sv-channels/blob/f14c3dd151907fdcb43f3dc4b88a92773a6a174d/scripts/genome_wide/functions.py#L600  so here  `length - 1` stored

hence updated code
https://github.com/GooglingTheCancerGenome/sv-channels/blob/6e9798765e36eaa6d710de827b23d827ab89e745/scripts/genome_wide/functions.py#L596

**Comment by lsantuari** [comment]
> length - 1

[length - 1 is correct](https://github.com/GooglingTheCancerGenome/sv-channels/blob/27a24d578e34469af092d17f334ea70cdb79a548/scripts/genome_wide/label_windows.py#L352)
