### ISSUE TITLE
Generate chromosome arrays from channel scripts

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#8]
- [x] `clipped_read_pos`, `clipped_reads` and `split_reads` on the entire BAM file
- [x] `coverage`, `clipped_read_distance`, `snv` per and `chr_array` chromosome

**Comment by arnikz** [comment]
@lsantuari: I can't find `bcolz_carray` in the repo.

**Comment by lsantuari** [comment]
Here 'bcolz_carray' refers to the script [chr_array](https://github.com/GooglingTheCancerGenome/CNN/blob/dev/scripts/genome_wide/chr_array.py). This script generates the arrays (one per chromosome, shape=(n_channels, chr_length)) in [bcolz carray](https://github.com/Blosc/bcolz/blob/master/docs/tutorial_carray.ipynb) format.

**Comment by arnikz** [comment]
I'm not sure what `chr_array` does. Also, I failed to run it with [test](https://github.com/GooglingTheCancerGenome/CNN/tree/iss6/data/test) data.

```
$ python chr_array.py --bam ../../data/test/hmz-sv.bam --chr 17.1 -o chr_array.npy.gz -p . -s .
Traceback (most recent call last):
  File "chr_array.py", line 392, in <module>
    main()
  File "chr_array.py", line 380, in main
    cmd_name=cmd_name
  File "chr_array.py", line 180, in create_hdf5
    channel_data = load_channels(sampleName, [chrom], outDir)
  File "chr_array.py", line 131, in load_channels
    channel_data[chrom]['split_reads'] = split_reads[chrom]
KeyError: '17.1'
```

It has some additional options including hard-coded input (e.g. .bigWig, .json.gz, `load_candidate_positions` is not used?). Could you add some IO details to wiki?

**Comment by lsantuari** [comment]
_load_candidate_positions_ is not used and can be removed.

I added a [Wiki page](https://github.com/GooglingTheCancerGenome/CNN/wiki/Generation-of-chromosome-arrays) for the chr_array script.

**Comment by arnikz** [comment]
All scripts are now used in 9be6d72028629129729c76c36b8fa1ace28c3095. However, some _channels_  in `chr_array` had to be disabled to pass. I've opened a separate issue #16  to fix those.
