### ISSUE TITLE
Replace Ns_to_bed.py with seqkit

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#80]
```
$ cat test.fasta 
>1
ATTGCNNTTTNNNCGNGG
>2
NNNAAATTGGNACGTACN

$ seqkit locate -i -P -r -p "N+" --bed test.fasta
1       5       7       N+      0       +
1       10      13      N+      0       +
1       15      16      N+      0       +
2       0       3       N+      0       +
2       10      11      N+      0       +
2       17      18      N+      0       +

$ python Ns_to_bed.py -b test.bed -t test.2bit -c 1,2
$ cat test.bed 
1	5	7
1	10	13
1	15	16
2	0	3
2	10	1
# Note: last line missing for the trailing 'N' in the sequence 2.
```
related to #76

**Comment by lsantuari** [comment]
> ```
> $ cat test.fasta 
> >1
> ATTGCNNTTTNNNCGNGG
> >2
> NNNAAATTGGNACGTACN
> 
> $ seqkit locate -i -P -r -p "N+" --bed test.fasta
> 1       5       7       N+      0       +
> 1       10      13      N+      0       +
> 1       15      16      N+      0       +
> 2       0       3       N+      0       +
> 2       10      11      N+      0       +
> 2       17      18      N+      0       +
> 
> $ python Ns_to_bed.py -b test.bed -t test.2bit -c 1,2
> $ cat test.bed 
> 1	5	7
> 1	10	13
> 1	15	16
> 2	0	3
> 2	10	1
> # Note: last line missing for the trailing 'N' in the sequence 2.
> ```
> 
> related to #76

@arnikz Thank you for finding the mistake. Let us use your seqkit command. I can adapt the R script accordingly.

**Comment by arnikz** [comment]
> I can adapt the R script accordingly.

Which script do you mean? Please open an issue.

**Comment by lsantuari** [comment]
> > I can adapt the R script accordingly.
> 
> Which script do you mean? Please open an issue.

see #81
